gtk_print_unix_dialog support added

diff --git a/gtkwave3/configure b/gtkwave3/configure
--- a/gtkwave3/configure
+++ b/gtkwave3/configure
@@ -615,6 +615,8 @@ ALLOCA
 EGREP
 GREP
 CPP
+GTK_UNIX_PRINT_LIBS
+GTK_UNIX_PRINT_CFLAGS
 GCONF_LIBS
 GCONF_CFLAGS
 COCOA_GTK_LDFLAGS
@@ -799,6 +801,8 @@ GTK_MAC_CFLAGS
 GTK_MAC_LIBS
 GCONF_CFLAGS
 GCONF_LIBS
+GTK_UNIX_PRINT_CFLAGS
+GTK_UNIX_PRINT_LIBS
 CPP'
 
 
@@ -1477,6 +1481,10 @@ Some influential environment variables:
   GCONF_CFLAGS
               C compiler flags for GCONF, overriding pkg-config
   GCONF_LIBS  linker flags for GCONF, overriding pkg-config
+  GTK_UNIX_PRINT_CFLAGS
+              C compiler flags for GTK_UNIX_PRINT, overriding pkg-config
+  GTK_UNIX_PRINT_LIBS
+              linker flags for GTK_UNIX_PRINT, overriding pkg-config
   CPP         C preprocessor
 
 Use these variables to override the choices made by `configure' or to help
@@ -6455,6 +6463,83 @@ fi
 
 	fi
 
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTK_UNIX_PRINT" >&5
+$as_echo_n "checking for GTK_UNIX_PRINT... " >&6; }
+
+if test -n "$GTK_UNIX_PRINT_CFLAGS"; then
+    pkg_cv_GTK_UNIX_PRINT_CFLAGS="$GTK_UNIX_PRINT_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-unix-print-2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-unix-print-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK_UNIX_PRINT_CFLAGS=`$PKG_CONFIG --cflags "gtk+-unix-print-2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTK_UNIX_PRINT_LIBS"; then
+    pkg_cv_GTK_UNIX_PRINT_LIBS="$GTK_UNIX_PRINT_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-unix-print-2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-unix-print-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTK_UNIX_PRINT_LIBS=`$PKG_CONFIG --libs "gtk+-unix-print-2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTK_UNIX_PRINT_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "gtk+-unix-print-2.0" 2>&1`
+        else
+	        GTK_UNIX_PRINT_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "gtk+-unix-print-2.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTK_UNIX_PRINT_PKG_ERRORS" >&5
+
+	GUP_F="no"
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	GUP_F="no"
+else
+	GTK_UNIX_PRINT_CFLAGS=$pkg_cv_GTK_UNIX_PRINT_CFLAGS
+	GTK_UNIX_PRINT_LIBS=$pkg_cv_GTK_UNIX_PRINT_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GUP_F="yes"
+fi
+	if test "x$GUP_F" = xyes; then
+		GTK_UNIX_PRINT_CFLAGS="${GTK_UNIX_PRINT_CFLAGS} -DWAVE_GTK_UNIX_PRINT"
+	fi
+
+
+
 fi
 
 # Checks for header files.
@@ -9207,104 +9292,112 @@ ac_config_files="$ac_config_files Makefile doc/Makefile contrib/Makefile contrib
 --------------------------------------------
   Configuration summary:
 
-  FASTTREE_CFLAGS   : $FASTTREE_CFLAGS
+  FASTTREE_CFLAGS       : $FASTTREE_CFLAGS
 
-  gtk1              : $GTK1
-  gtk version       : $GTK_VER
-  GTK_CFLAGS        : $GTK_CFLAGS
-  GTK_LIBS          : $GTK_LIBS
+  gtk1                  : $GTK1
+  gtk version           : $GTK_VER
+  GTK_CFLAGS            : $GTK_CFLAGS
+  GTK_LIBS              : $GTK_LIBS
 
-  LIBZ_CFLAGS       : $LIBZ_CFLAGS
-  LIBZ_LDADD        : $LIBZ_LDADD
+  LIBZ_CFLAGS           : $LIBZ_CFLAGS
+  LIBZ_LDADD            : $LIBZ_LDADD
 
-  LIBBZ2_CFLAGS     : $LIBBZ2_CFLAGS
-  LIBBZ2_LDADD      : $LIBBZ2_LDADD
+  LIBBZ2_CFLAGS         : $LIBBZ2_CFLAGS
+  LIBBZ2_LDADD          : $LIBBZ2_LDADD
 
-  LIBXZ_CFLAGS      : $LIBXZ_CFLAGS
-  LIBXZ_LDADD       : $LIBXZ_LDADD
+  LIBXZ_CFLAGS          : $LIBXZ_CFLAGS
+  LIBXZ_LDADD           : $LIBXZ_LDADD
 
-  LIBJUDY_CFLAGS    : $LIBJUDY_CFLAGS
-  LIBJUDY_LDADD     : $LIBJUDY_LDADD
+  LIBJUDY_CFLAGS        : $LIBJUDY_CFLAGS
+  LIBJUDY_LDADD         : $LIBJUDY_LDADD
 
-  AET2_CFLAGS       : $AET2_CFLAGS
-  AET2_LDADD        : $AET2_LDADD
+  AET2_CFLAGS           : $AET2_CFLAGS
+  AET2_LDADD            : $AET2_LDADD
 
-  EXTLOAD_CFLAGS    : $EXTLOAD_CFLAGS
+  EXTLOAD_CFLAGS        : $EXTLOAD_CFLAGS
 
-  TCL_INCLUDE_SPEC  : $TCL_INCLUDE_SPEC
-  TCL_LIB_SPEC      : $TCL_LIB_SPEC
-  TCL_LDADD         : $TCL_LDADD
-  TCL_DEFADD        : $TCL_DEFADD
+  TCL_INCLUDE_SPEC      : $TCL_INCLUDE_SPEC
+  TCL_LIB_SPEC          : $TCL_LIB_SPEC
+  TCL_LDADD             : $TCL_LDADD
+  TCL_DEFADD            : $TCL_DEFADD
 
-  TK_INCLUDE_SPEC   : $TK_INCLUDE_SPEC
-  TK_LIB_SPEC       : $TK_LIB_SPEC
-  TK_LDADD          : $TK_LDADD
+  TK_INCLUDE_SPEC       : $TK_INCLUDE_SPEC
+  TK_LIB_SPEC           : $TK_LIB_SPEC
+  TK_LDADD              : $TK_LDADD
 
-  CPPFLAGS          : $CPPFLAGS
-  CFLAGS            : $CFLAGS
-  LDFLAGS           : $LDFLAGS
-  LIBS              : $LIBS
-  INLINE_ASM        : $INLINE_ASM
-  GTK_MAC_CFLAGS    : $GTK_MAC_CFLAGS
-  GTK_MAC_LIBS      : $GTK_MAC_LIBS
-  GCONF_CFLAGS      : $GCONF_CFLAGS
-  GCONF_LIBS        : $GCONF_LIBS
-  COCOA_GTK_CFLAGS  : $COCOA_GTK_CFLAGS
-  COCOA_GTK_LDADD   : $COCOA_GTK_LDADD
-  COCOA_GTK_LDFLAGS : $COCOA_GTK_LDFLAGS
+  CPPFLAGS              : $CPPFLAGS
+  CFLAGS                : $CFLAGS
+  LDFLAGS               : $LDFLAGS
+  LIBS                  : $LIBS
+  INLINE_ASM            : $INLINE_ASM
 
+  GTK_MAC_CFLAGS        : $GTK_MAC_CFLAGS
+  GTK_MAC_LIBS          : $GTK_MAC_LIBS
+  COCOA_GTK_CFLAGS      : $COCOA_GTK_CFLAGS
+  COCOA_GTK_LDADD       : $COCOA_GTK_LDADD
+  COCOA_GTK_LDFLAGS     : $COCOA_GTK_LDFLAGS
+
+  GCONF_CFLAGS          : $GCONF_CFLAGS
+  GCONF_LIBS            : $GCONF_LIBS
+
+  GTK_UNIX_PRINT_CFLAGS : $GTK_UNIX_PRINT_CFLAGS
+  GTK_UNIX_PRINT_LIBS   : $GTK_UNIX_PRINT_LIBS
 --------------------------------------------
 " >&5
 $as_echo "$as_me:
 --------------------------------------------
   Configuration summary:
 
-  FASTTREE_CFLAGS   : $FASTTREE_CFLAGS
+  FASTTREE_CFLAGS       : $FASTTREE_CFLAGS
 
-  gtk1              : $GTK1
-  gtk version       : $GTK_VER
-  GTK_CFLAGS        : $GTK_CFLAGS
-  GTK_LIBS          : $GTK_LIBS
+  gtk1                  : $GTK1
+  gtk version           : $GTK_VER
+  GTK_CFLAGS            : $GTK_CFLAGS
+  GTK_LIBS              : $GTK_LIBS
 
-  LIBZ_CFLAGS       : $LIBZ_CFLAGS
-  LIBZ_LDADD        : $LIBZ_LDADD
+  LIBZ_CFLAGS           : $LIBZ_CFLAGS
+  LIBZ_LDADD            : $LIBZ_LDADD
 
-  LIBBZ2_CFLAGS     : $LIBBZ2_CFLAGS
-  LIBBZ2_LDADD      : $LIBBZ2_LDADD
+  LIBBZ2_CFLAGS         : $LIBBZ2_CFLAGS
+  LIBBZ2_LDADD          : $LIBBZ2_LDADD
 
-  LIBXZ_CFLAGS      : $LIBXZ_CFLAGS
-  LIBXZ_LDADD       : $LIBXZ_LDADD
+  LIBXZ_CFLAGS          : $LIBXZ_CFLAGS
+  LIBXZ_LDADD           : $LIBXZ_LDADD
 
-  LIBJUDY_CFLAGS    : $LIBJUDY_CFLAGS
-  LIBJUDY_LDADD     : $LIBJUDY_LDADD
+  LIBJUDY_CFLAGS        : $LIBJUDY_CFLAGS
+  LIBJUDY_LDADD         : $LIBJUDY_LDADD
 
-  AET2_CFLAGS       : $AET2_CFLAGS
-  AET2_LDADD        : $AET2_LDADD
+  AET2_CFLAGS           : $AET2_CFLAGS
+  AET2_LDADD            : $AET2_LDADD
 
-  EXTLOAD_CFLAGS    : $EXTLOAD_CFLAGS
+  EXTLOAD_CFLAGS        : $EXTLOAD_CFLAGS
 
-  TCL_INCLUDE_SPEC  : $TCL_INCLUDE_SPEC
-  TCL_LIB_SPEC      : $TCL_LIB_SPEC
-  TCL_LDADD         : $TCL_LDADD
-  TCL_DEFADD        : $TCL_DEFADD
+  TCL_INCLUDE_SPEC      : $TCL_INCLUDE_SPEC
+  TCL_LIB_SPEC          : $TCL_LIB_SPEC
+  TCL_LDADD             : $TCL_LDADD
+  TCL_DEFADD            : $TCL_DEFADD
 
-  TK_INCLUDE_SPEC   : $TK_INCLUDE_SPEC
-  TK_LIB_SPEC       : $TK_LIB_SPEC
-  TK_LDADD          : $TK_LDADD
+  TK_INCLUDE_SPEC       : $TK_INCLUDE_SPEC
+  TK_LIB_SPEC           : $TK_LIB_SPEC
+  TK_LDADD              : $TK_LDADD
 
-  CPPFLAGS          : $CPPFLAGS
-  CFLAGS            : $CFLAGS
-  LDFLAGS           : $LDFLAGS
-  LIBS              : $LIBS
-  INLINE_ASM        : $INLINE_ASM
-  GTK_MAC_CFLAGS    : $GTK_MAC_CFLAGS
-  GTK_MAC_LIBS      : $GTK_MAC_LIBS
-  GCONF_CFLAGS      : $GCONF_CFLAGS
-  GCONF_LIBS        : $GCONF_LIBS
-  COCOA_GTK_CFLAGS  : $COCOA_GTK_CFLAGS
-  COCOA_GTK_LDADD   : $COCOA_GTK_LDADD
-  COCOA_GTK_LDFLAGS : $COCOA_GTK_LDFLAGS
+  CPPFLAGS              : $CPPFLAGS
+  CFLAGS                : $CFLAGS
+  LDFLAGS               : $LDFLAGS
+  LIBS                  : $LIBS
+  INLINE_ASM            : $INLINE_ASM
 
+  GTK_MAC_CFLAGS        : $GTK_MAC_CFLAGS
+  GTK_MAC_LIBS          : $GTK_MAC_LIBS
+  COCOA_GTK_CFLAGS      : $COCOA_GTK_CFLAGS
+  COCOA_GTK_LDADD       : $COCOA_GTK_LDADD
+  COCOA_GTK_LDFLAGS     : $COCOA_GTK_LDFLAGS
+
+  GCONF_CFLAGS          : $GCONF_CFLAGS
+  GCONF_LIBS            : $GCONF_LIBS
+
+  GTK_UNIX_PRINT_CFLAGS : $GTK_UNIX_PRINT_CFLAGS
+  GTK_UNIX_PRINT_LIBS   : $GTK_UNIX_PRINT_LIBS
 --------------------------------------------
 " >&6;}
 
